# Generated by Django 5.2 on 2026-03-25 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_jobcategory_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='mainapp.job')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='mainapp.jobseeker')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'jobseeker'), name='unique_saved_job')],
            },
        ),
    ]
